config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  devise_for :users
  
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]# resource(単数)だとURLにidが入らない
    resources :book_comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  #検索ボタンが押されたらSearchesコントローラーのsearchアクション実行
  get "search" => "searches#search"
  
  resources :chats, only: [:show, :create]
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id
  #同じユーザーが同じ本に対して複数のコメントを投稿できない(一意性をチェック)
    
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    
  # 非同期通信化によりredirect削除  
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    # redirect_to request.referer
  end
  
  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    # redirect_to request.referer
  end    
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_btn.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete do %>
    <i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
    <%= book.favorites.count %> いいね
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post do %>
    <i class="fas fa-heart" aria-hidden="true"></i>
    <%= book.favorites.count %> いいね
  <% end %>
<% end %>

app/views/favorites/_favorite-btn.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book_id: book.id), method: :delete, remote: true do %>
    <i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
    <%= book.favorites.count %> いいね
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book_id: book.id), method: :post, remote: true do %>
    <i class="fas fa-heart" aria-hidden="true"></i>
    <%= book.favorites.count %> いいね
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$('#favorite_btn<%= @book.id %>').html("<%= j(render "favorites/favorite-btn", book: @book) %>");
<!--idがbook_〇の要素の中の、favorite-btnクラスの要素-->

<!--$(".favorite-btn").html("%= escape_javascript(render partial: 'favorites/favorite-btn', locals: {book: @book}) %>");-->

  <!--// インスタンス変数は、favorites_controllerのcreateアクションで定義されたものが使用できます。-->
  <!--// 以下の記述でも同じ挙動をします。html()以降では部分テンプレートを呼び出しています。-->
  <!--$(".favorite-btn").html("%= j(render 'favorites/favorite-btn', book: @book) %>");#-->

app/views/favorites/destroy.js.erb
$('#favorite_btn<%= @book.id %>').html("<%= j(render "favorites/favorite-btn", book: @book) %>");