config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  devise_for :users
  
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]# resource(単数)だとURLにidが入らない
    resources :book_comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  #検索ボタンが押されたらSearchesコントローラーのsearchアクション実行
  get "search" => "searches#search"
  
  resources :chats, only: [:show, :create]
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
    
  def create
    @book = Book.find(params[:book_id])
    comment = BookComment.new(book_comment_params)
    comment.user_id = current_user.id
    comment.book_id = @book.id
    comment.save
    #redirect_to book_path(book)
  end
    
  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end
    
  private
    
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end    
  
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_index.html.erb
<table>
  <tbody>
  <% book.book_comments.each do |book_comment| %>
  <tr>
    <td><%= link_to user_path(book_comment.user) do %>
      <%= image_tag book_comment.user.get_profile_image, size:"100x100" %><br>
      <%= book_comment.user.name %>
    <% end %>
    </td>
    <td>
      <%= book_comment.comment %>
    </td>
    <td>
      <% if book_comment.user == current_user %>
      <%= link_to "Destroy", book_book_comment_path(book, book_comment), method: :delete, class: "btn btn-danger pull-right" %>
      <% end %>
    </td>
  </tr>
  <% end %>
</tbody>
</table>

app/views/book_comments/create.js.erb
$("#book_<%= @book.id %> .comments-count").html("コメント数: <%= @book.book_comments.count %>");
$(".book_comments").html("<%= j(render 'book_comments/index', book: @book) %>");

$("#book_comment_comment").val("");

app/views/book_comments/destroy.js.erb
$("#book_<%= @book.id %> .comments-count").html("コメント数: <%= @book.book_comments.count %>");
$(".book_comments").html("<%= j(render 'book_comments/index', book: @book) %>");